.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/network Directory Reference" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/network Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\&.h\fP"
.br
.ti -1c
.RI "file \fBget_data\&.h\fP"
.br
.ti -1c
.RI "file \fBnetwork\&.h\fP"
.br
.ti -1c
.RI "file \fBsend_data\&.h\fP"
.br
.ti -1c
.RI "file \fBserver\&.h\fP"
.br
.in -1c
