.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src Directory Reference" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient\&.c\fP"
.br
.ti -1c
.RI "file \fBgenesis\&.c\fP"
.br
.ti -1c
.RI "file \fBserverdoor\&.c\fP"
.br
.in -1c
