.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/blockchain Directory Reference" 3 "Tue Apr 20 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/blockchain Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBblock\&.h\fP"
.br
.ti -1c
.RI "file \fBtransaction\&.h\fP"
.br
.ti -1c
.RI "file \fBwallet\&.h\fP"
.br
.in -1c
