.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/blockchain_header.c" 3 "Fri Jun 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/blockchain_header.c
.SH SYNOPSIS
.br
.PP
\fC#include 'blockchain/blockchain_header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwrite_block_header\fP (FILE *fd, \fBBlock\fP *block, size_t height)"
.br
.ti -1c
.RI "void \fBgen_blockchain_header\fP (\fBinfos_st\fP *infos)"
.br
.RI "Generate block shared information\&. "
.ti -1c
.RI "size_t \fBget_receiver_remaining_money\fP (\fBinfos_st\fP *infos, RSA *receiver_public_key)"
.br
.RI "Get the receiver remaining money\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gen_blockchain_header (\fBinfos_st\fP * infos)"

.PP
Generate block shared information\&. 
.PP
\fBDeprecated\fP
.RS 4

.RE
.PP
\fBParameters\fP
.RS 4
\fIinfos\fP The information 
.RE
.PP

.PP
Definition at line 9 of file blockchain_header\&.c\&.
.SS "size_t get_receiver_remaining_money (\fBinfos_st\fP * infos, RSA * receiver_public_key)"

.PP
Get the receiver remaining money\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfos\fP Threads shared information 
.br
\fIreceiver_public_key\fP The RSA public key of the receiver 
.RE
.PP
\fBReturns\fP
.RS 4
size_t 
.RE
.PP

.PP
Definition at line 40 of file blockchain_header\&.c\&.
.SS "void write_block_header (FILE * fd, \fBBlock\fP * block, size_t height)"

.PP
Definition at line 3 of file blockchain_header\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
