.TH "blockinfo" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blockinfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "size_t \fBtransactions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file ui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t height"

.PP
Definition at line 28 of file ui\&.h\&.
.SS "size_t transactions"

.PP
Definition at line 29 of file ui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
