.TH "Block" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBchunk_id\fP"
.br
.ti -1c
.RI "\fBBlockData\fP \fBblock_data\fP"
.br
.ti -1c
.RI "char \fBblock_signature\fP [256]"
.br
.ti -1c
.RI "char \fBvalidators_votes\fP [\fBMAX_VALIDATORS_PER_BLOCK\fP/8]"
.br
.ti -1c
.RI "char \fBvote_signature\fP [\fBMAX_VALIDATORS_PER_BLOCK\fP \- 1][256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file block\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBlockData\fP block_data"

.PP
Definition at line 54 of file block\&.h\&.
.SS "char block_signature[256]"

.PP
Definition at line 56 of file block\&.h\&.
.SS "uint16_t chunk_id"

.PP
Definition at line 53 of file block\&.h\&.
.SS "char validators_votes[\fBMAX_VALIDATORS_PER_BLOCK\fP/8]"

.PP
Definition at line 59 of file block\&.h\&.
.SS "char vote_signature[\fBMAX_VALIDATORS_PER_BLOCK\fP \- 1][256]"

.PP
Definition at line 60 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
