.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/src/blockchain/block_test.c" 3 "Tue Jun 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/src/blockchain/block_test.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tests_macros\&.h'\fP
.br
\fC#include 'blockchain/block\&.h'\fP
.br
\fC#include 'blockchain/transaction\&.h'\fP
.br
\fC#include 'gen/GEN_blockchain_files\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBLOCK_TEST_C\fP"
.br
.ti -1c
.RI "#define \fBNB_BLOCK_PER_CHUNK\fP   10"
.br
.ti -1c
.RI "#define \fBNB_MOCK_BLOCKS\fP   13"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBblock_test\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOCK_TEST_C"

.PP
Definition at line 2 of file block_test\&.c\&.
.SS "#define NB_BLOCK_PER_CHUNK   10"

.PP
Definition at line 9 of file block_test\&.c\&.
.SS "#define NB_MOCK_BLOCKS   13"

.PP
Definition at line 11 of file block_test\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void block_test (void)"

.PP
Definition at line 13 of file block_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
