.TH "Block" 3 "Sat Apr 10 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBchunk_id\fP"
.br
.ti -1c
.RI "\fBBlockData\fP \fBblock_data\fP"
.br
.ti -1c
.RI "size_t \fBsignature_len\fP"
.br
.ti -1c
.RI "char * \fBblock_signature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file block\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBlockData\fP block_data"

.PP
Definition at line 34 of file block\&.h\&.
.SS "char* block_signature"

.PP
Definition at line 37 of file block\&.h\&.
.SS "uint16_t chunk_id"

.PP
Definition at line 33 of file block\&.h\&.
.SS "size_t signature_len"

.PP
Definition at line 36 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
