.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/blockchain/blockchain_header.h" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/blockchain/blockchain_header.h
.SH SYNOPSIS
.br
.PP
\fC#include 'blockchain/block\&.h'\fP
.br
\fC#include 'network/network\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgen_blockchain_header\fP (\fBinfos_st\fP *infos)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gen_blockchain_header (\fBinfos_st\fP * infos)"

.PP
Definition at line 9 of file blockchain_header\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
