.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/blockchain_header.c" 3 "Sun May 9 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/blockchain_header.c
.SH SYNOPSIS
.br
.PP
\fC#include 'blockchain/blockchain_header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwrite_block_header\fP (FILE *fd, \fBBlock\fP *block, size_t height)"
.br
.ti -1c
.RI "void \fBgen_blockchain_header\fP (\fBinfos_st\fP *infos)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gen_blockchain_header (\fBinfos_st\fP * infos)"

.PP
Definition at line 9 of file blockchain_header\&.c\&.
.SS "void write_block_header (FILE * fd, \fBBlock\fP * block, size_t height)"

.PP
Definition at line 3 of file blockchain_header\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
