.TH "ChunkBlockchain" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkBlockchain
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBchunk_nb\fP"
.br
.ti -1c
.RI "\fBBlock\fP ** \fBchunk\fP"
.br
.ti -1c
.RI "int16_t \fBnb_blocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file block\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBlock\fP** chunk"

.PP
Definition at line 66 of file block\&.h\&.
.SS "size_t chunk_nb"

.PP
Definition at line 65 of file block\&.h\&.
.SS "int16_t nb_blocks"

.PP
Definition at line 67 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
