.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/src/network/client_test.c" 3 "Sat Apr 17 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/src/network/client_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <signal\&.h>\fP
.br
\fC#include 'tests_macros\&.h'\fP
.br
\fC#include 'network/network\&.h'\fP
.br
\fC#include 'network/client\&.h'\fP
.br
\fC#include 'network/server\&.h'\fP
.br
\fC#include 'network/send_data\&.h'\fP
.br
\fC#include 'network/get_data\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnetwork_test\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void network_test ()"

.PP
Definition at line 10 of file client_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
