.TH "client_connection" 3 "Thu Apr 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_connection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct addrinfo \fBinfo\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file server\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct addrinfo info"

.PP
Definition at line 10 of file server\&.h\&.
.SS "int socket"

.PP
Definition at line 11 of file server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
