.TH "connection" 3 "Sun Jul 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_t \fBthread\fP"
.br
.ti -1c
.RI "sem_t \fBlock\fP"
.br
.ti -1c
.RI "int \fBdemand\fP"
.br
.ti -1c
.RI "int \fBclientfd\fP"
.br
.ti -1c
.RI "size_t \fBPayloadsize\fP"
.br
.ti -1c
.RI "void * \fBPayload\fP"
.br
.ti -1c
.RI "size_t \fBactual_client_height\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file network\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t actual_client_height"

.PP
Definition at line 52 of file network\&.h\&.
.SS "int clientfd"

.PP
Definition at line 49 of file network\&.h\&.
.SS "int demand"

.PP
Definition at line 48 of file network\&.h\&.
.SS "sem_t lock"

.PP
Definition at line 47 of file network\&.h\&.
.SS "void* Payload"

.PP
Definition at line 51 of file network\&.h\&.
.SS "size_t Payloadsize"

.PP
Definition at line 50 of file network\&.h\&.
.SS "pthread_t thread"

.PP
Definition at line 46 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
