.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/epoch_man.c" 3 "Sun May 9 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/epoch_man.c
.SH SYNOPSIS
.br
.PP
\fC#include 'validation/epoch_man\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "RSA * \fBget_epoch_man_pkey\fP (\fBBlockData\fP *block_data)"
.br
.RI "Give the pkey of the creator of a block\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "RSA* get_epoch_man_pkey (\fBBlockData\fP * block_data)"

.PP
Give the pkey of the creator of a block\&. 
.PP
\fBParameters\fP
.RS 4
\fIblock_data\fP The created block data 
.RE
.PP
\fBReturns\fP
.RS 4
RSA* 
.RE
.PP

.PP
Definition at line 3 of file epoch_man\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
