.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/validation/epoch_man.h" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/validation/epoch_man.h
.SH SYNOPSIS
.br
.PP
\fC#include 'blockchain/transaction\&.h'\fP
.br
\fC#include 'blockchain/block\&.h'\fP
.br
\fC#include 'cryptosystem/signature\&.h'\fP
.br
\fC#include 'validation_engine\&.h'\fP
.br
\fC#include 'misc/bits\&.h'\fP
.br
\fC#include 'validators\&.h'\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcreate_vote_data\fP (\fBBlock\fP *block, char vote, int validator_index, size_t *data_length)"
.br
.ti -1c
.RI "\fBBlock\fP * \fBcreate_epoch_block\fP ()"
.br
.RI "Create a block object with the previous block hash & votes\&. "
.ti -1c
.RI "RSA * \fBget_epoch_man_pkey\fP (\fBBlockData\fP *block_data)"
.br
.RI "Give the pkey of the creator of a block\&. "
.ti -1c
.RI "void \fBgive_punishments_and_rewards\fP (\fBBlock\fP *prev_block, \fBBlock\fP *current_block)"
.br
.RI "Add punishmnent and reward transactions to validators of the 'prev_block' into 'current_block'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBlock\fP* create_epoch_block ()"

.PP
Create a block object with the previous block hash & votes\&. 
.PP
\fBSee also\fP
.RS 4
The function create a block based on the local last block
.RE
.PP
\fBReturns\fP
.RS 4
Block* 
.RE
.PP

.PP
Definition at line 141 of file epoch_man\&.c\&.
.SS "char* create_vote_data (\fBBlock\fP * block, char vote, int validator_index, size_t * data_length)"

.PP
Definition at line 10 of file epoch_man\&.c\&.
.SS "RSA* get_epoch_man_pkey (\fBBlockData\fP * block_data)"

.PP
Give the pkey of the creator of a block\&. 
.PP
\fBParameters\fP
.RS 4
\fIblock_data\fP The created block data 
.RE
.PP
\fBReturns\fP
.RS 4
RSA*, NULL if the data is corrupted 
.RE
.PP

.PP
Definition at line 3 of file epoch_man\&.c\&.
.SS "void give_punishments_and_rewards (\fBBlock\fP * prev_block, \fBBlock\fP * current_block)"

.PP
Add punishmnent and reward transactions to validators of the 'prev_block' into 'current_block'\&. 
.PP
\fBSee also\fP
.RS 4
Number of added transactions = number of validators in 'prev_block'
.RE
.PP
\fBParameters\fP
.RS 4
\fIprev_block\fP The last validated block 
.br
\fIcurrent_block\fP The current block (in creation) 
.RE
.PP

.PP
Definition at line 31 of file epoch_man\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
