.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/gen/GEN_blockchain_files.c" 3 "Mon Apr 19 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/gen/GEN_blockchain_files.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tests_macros\&.h'\fP
.br
\fC#include 'core/blockchain/block\&.h'\fP
.br
\fC#include 'core/blockchain/transaction\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBrand_data\fP (size_t size)"
.br
.ti -1c
.RI "void \fBgen_blockhain\fP (size_t nb_blocks)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gen_blockhain (size_t nb_blocks)"

.PP
Definition at line 20 of file GEN_blockchain_files\&.c\&.
.SS "void* rand_data (size_t size)"

.PP
Definition at line 5 of file GEN_blockchain_files\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
