.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/network/get_data.h" 3 "Sat May 8 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/network/get_data.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'network/network\&.h'\fP
.br
\fC#include 'network/client\&.h'\fP
.br
\fC#include 'network/server\&.h'\fP
.br
\fC#include 'network/send_data\&.h'\fP
.br
\fC#include 'ui/ui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBread_header\fP (int sockfd, \fBinfos_st\fP *infos)"
.br
.RI "Waits a header in 'sockfd', reads it and processes it\&. "
.ti -1c
.RI "int \fBfetch_client_list\fP (char who, int fd)"
.br
.RI "Merges my neighbours list with the one sent by 'neighbour_id'\&. "
.ti -1c
.RI "int \fBread_get_blocks\fP (int fd, \fBinfos_st\fP *infos)"
.br
.ti -1c
.RI "size_t \fBread_actual_height\fP (int fd)"
.br
.ti -1c
.RI "int \fBread_send_block\fP (int fd)"
.br
.ti -1c
.RI "int \fBread_vote\fP (int fd)"
.br
.ti -1c
.RI "int \fBread_pending_transaction_list\fP (int fd)"
.br
.ti -1c
.RI "int \fBread_epoch_block\fP (int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int fetch_client_list (char who, int fd)"

.PP
Merges my neighbours list with the one sent by 'neighbour_id'\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockfd\fP The sockfd to read
.RE
.PP
\fBReturns\fP
.RS 4
0 if sucess, -1 otherwise 
.RE
.PP

.PP
Definition at line 95 of file get_data\&.c\&.
.SS "size_t read_actual_height (int fd)"

.PP
Definition at line 172 of file get_data\&.c\&.
.SS "int read_epoch_block (int fd)"

.PP
Definition at line 222 of file get_data\&.c\&.
.SS "int read_get_blocks (int fd, \fBinfos_st\fP * infos)"

.PP
Definition at line 144 of file get_data\&.c\&.
.SS "size_t read_header (int sockfd, \fBinfos_st\fP * infos)"

.PP
Waits a header in 'sockfd', reads it and processes it\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockfd\fP The sock FD 
.RE
.PP
\fBReturns\fP
.RS 4
0 if sucess, -1 otherwise 
.RE
.PP

.PP
Definition at line 125 of file get_data\&.c\&.
.SS "int read_pending_transaction_list (int fd)"

.SS "int read_send_block (int fd)"

.PP
Definition at line 178 of file get_data\&.c\&.
.SS "int read_vote (int fd)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
