.TH "infos_st" 3 "Tue Jun 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
infos_st
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBas_epoch\fP"
.br
.ti -1c
.RI "char \fBis_validator\fP"
.br
.ti -1c
.RI "int \fBvalidator_id\fP"
.br
.ti -1c
.RI "size_t \fBactual_height\fP"
.br
.ti -1c
.RI "size_t \fBpdt\fP"
.br
.ti -1c
.RI "char \fBserv_type\fP"
.br
.ti -1c
.RI "char \fBis_sychronize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file network\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t actual_height"

.PP
Definition at line 60 of file network\&.h\&.
.SS "char as_epoch"

.PP
Definition at line 57 of file network\&.h\&.
.SS "char is_sychronize"

.PP
Definition at line 10 of file unit_testing\&.c\&.
.SS "char is_validator"

.PP
Definition at line 58 of file network\&.h\&.
.SS "size_t pdt"

.PP
Definition at line 61 of file network\&.h\&.
.SS "char serv_type"

.PP
Definition at line 62 of file network\&.h\&.
.SS "int validator_id"

.PP
Definition at line 59 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
