.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/ui/labels.h" 3 "Fri Jun 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/ui/labels.h
.SH SYNOPSIS
.br
.PP
\fC#include <gtk/gtk\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchange_label_text\fP (GtkLabel *label, char *text)"
.br
.ti -1c
.RI "void \fBadd_new_blockinfo\fP (size_t height, size_t transaction)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "GtkLabel * \fBbalance_1\fP"
.br
.ti -1c
.RI "GtkLabel * \fBbalance_2\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label1\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label2\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label3\fP"
.br
.ti -1c
.RI "GtkLabel * \fBsynchro_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBblock_amount_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBconnections_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBmempool_label\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_new_blockinfo (size_t height, size_t transaction)"

.PP
Definition at line 322 of file ui\&.c\&.
.SS "void change_label_text (GtkLabel * label, char * text)"

.PP
Definition at line 233 of file ui\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "GtkLabel* balance_1\fC [extern]\fP"

.PP
Definition at line 24 of file ui\&.c\&.
.SS "GtkLabel* balance_2\fC [extern]\fP"

.PP
Definition at line 25 of file ui\&.c\&.
.SS "GtkLabel* block_amount_label\fC [extern]\fP"

.PP
Definition at line 30 of file ui\&.c\&.
.SS "GtkLabel* connections_label\fC [extern]\fP"

.PP
Definition at line 31 of file ui\&.c\&.
.SS "GtkLabel* mempool_label\fC [extern]\fP"

.PP
Definition at line 32 of file ui\&.c\&.
.SS "GtkLabel* stake_label1\fC [extern]\fP"

.PP
Definition at line 26 of file ui\&.c\&.
.SS "GtkLabel* stake_label2\fC [extern]\fP"

.PP
Definition at line 27 of file ui\&.c\&.
.SS "GtkLabel* stake_label3\fC [extern]\fP"

.PP
Definition at line 28 of file ui\&.c\&.
.SS "GtkLabel* synchro_label\fC [extern]\fP"

.PP
Definition at line 29 of file ui\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
