.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/misc/math.h" 3 "Mon Apr 19 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/misc/math.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIN\fP(a,  b)   ((a) < (b)) ? (a) : (b)"
.br
.ti -1c
.RI "#define \fBMAX\fP(a,  b)   ((a) > (b)) ? (a) : (b)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX(a, b)   ((a) > (b)) ? (a) : (b)"

.PP
Definition at line 2 of file math\&.h\&.
.SS "#define MIN(a, b)   ((a) < (b)) ? (a) : (b)"

.PP
Definition at line 1 of file math\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
