.TH "md__home_runner_work__p_e_p_i_t_a_s-_cryptocurrency__p_e_p_i_t_a_s-_cryptocurrency__p2_p__p_r_o_t_o_c_o_l" 3 "Tue Jun 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_runner_work__p_e_p_i_t_a_s-_cryptocurrency__p_e_p_i_t_a_s-_cryptocurrency__p2_p__p_r_o_t_o_c_o_l \- PEPITAS NETWORK PROTOCOL 

.SH "HEADERS"
.PP
.SS "Sync Headers"
.IP "1." 4
CONNECTION TO NETWORK
.IP "2." 4
CONNECTION TO NODE
.IP "3." 4
GET BLOCKS
.IP "4." 4
ACTUAL HEIGHT
.IP "5." 4
SEND BLOCK
.IP "6." 4
GET PENDING TRANSACTION LIST
.IP "7." 4
REJECT DEMAND 
.PP
.SS "Running Headers"
.IP "7." 4
SEND PENDING TRANSACTION 
.PP
.SS "Validating Headers"
.IP "9." 4
SEND BLOCK EPOCHMAN
.IP "10." 4
SEND VOTE
.PP
.SS "CONNECTION TO NETWORK"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'CONNECTION TO NETWORK\\r\\n\\r\\n'
.PP
.PP
\fBDescription\fP Send a request to be accepted by a network door\&.
.SS "CONNECTION TO NODE"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'CONNECTION TO NODE\\r\\n\\r\\n'
.PP
.PP
\fBDescription\fP Send a request to be accepted by a network node\&. 
.SS "GET BLOCKS"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'GET BLOCKS\\r\\n\\r\\n'
.IP "\(bu" 2
uint32_t : P_VERSION
.IP "\(bu" 2
char : Number of demand (max 50)
.IP "\(bu" 2
size_t * : \fBBlock\fP height
.PP
.PP
\fBDescription\fP Send a request to a server for getting blocks\&. If the genesis block (height 0) is demand then the number of the actual blockchain height is return with 'ACTUAL HEIGHT' header\&. If not, SEND BLOCK or REJECT DEMAND messages are returned\&. 
.SS "ACTUAL HEIGHT"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'ACTUAL HEIGHT\\r\\n\\r\\n'
.IP "\(bu" 2
size_t : \fBBlock\fP height
.PP
.PP
\fBDescription\fP Send my actual blockchain height\&. 
.SS "SEND BLOCK"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'SEND BLOCK\\r\\n\\r\\n'
.IP "\(bu" 2
size_t : \fBBlock\fP height
.IP "\(bu" 2
size_t : \fBBlock\fP size
.IP "\(bu" 2
char * : \fBBlock\fP struct
.PP
.PP
\fBDescription\fP The block of height demand by 'GET BLOCKS'\&. 
.SS "GET PENDING TRANSACTION LIST"
\fBMessage\fP
.IP "\(bu" 2
char * : 'GET PENDING TRANSACTION LIST\\r\\n\\r\\n'
.PP
.PP
\fBDescription\fP Call 'SEND PENDING TRANSACTION LIST'\&. 
.SS "SEND PENDING TRANSACTION LIST"
\fBMessage\fP
.IP "\(bu" 2
char * : 'GET PENDING TRANSACTION LIST\\r\\n\\r\\n'
.IP "\(bu" 2
size_t : Number of \fBTransaction\fP id
.IP "\(bu" 2
time_t * : \fBTransaction\fP id
.PP
.PP
\fBDescription\fP Send PDT list\&. 
.SS "REJECT DEMAND"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'REJECT DEMAND\\r\\n\\r\\n'
.PP
.PP
\fBDescription\fP Reject a demand if can't reply\&. For example a 'GET BLOCKS' of a not existing block\&.
.SS "GET PENDING TRANSACTION"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'GET PENDING TRANSACTION\\r\\n\\r\\n'
.IP "\(bu" 2
time_t : \fBTransaction\fP id
.PP
.PP
\fBDescription\fP Demand a PENDING TRANSACTION\&. 
.SS "SEND PENDING TRANSACTION"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'SEND PENDING TRANSACTION\\r\\n\\r\\n'
.IP "\(bu" 2
size_t : \fBTransaction\fP id
.IP "\(bu" 2
size_t : \fBTransaction\fP struct size octet
.IP "\(bu" 2
char * : \fBTransaction\fP struct
.PP
.PP
\fBDescription\fP Send the PENDING TRANSACTION demand by SEND PENDING TRANSACTION\&. 
.SS "SEND EPOCH BLOCK"
\fBMessage:\fP
.IP "\(bu" 2
char * : 'SEND EPOCH BLOCK\\r\\n\\r\\n'
.IP "\(bu" 2
int : Epoch id
.IP "\(bu" 2
size_t : \fBBlock\fP height
.IP "\(bu" 2
char * : \fBBlock\fP struct
.PP
.PP
\fBDescription\fP Send the epoch block of a committee member\&.
.SS "SEND VOTE"
\fBMessage:\fP
.PP
.IP "\(bu" 2
char * : 'SEND VOTE\\r\\n\\r\\n'
.IP "\(bu" 2
size_t : size epoch creator pk
.IP "\(bu" 2
char * : Epoch creator pk
.IP "\(bu" 2
size_t : block height
.IP "\(bu" 2
int : epoch_id
.IP "\(bu" 2
char : 0 = False 1 = True
.IP "\(bu" 2
char * : signature of vote precedent vars but not 'SEND VOTE\\r\\n\\r\\n'
.PP
.PP
\fBDescription\fP Send the vote of a committee member\&. 
