.TH "md__home_runner_work__p_e_p_i_t_a_s-_cryptocurrency__p_e_p_i_t_a_s-_cryptocurrency__r_e_a_d_m_e" 3 "Fri Apr 16 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_runner_work__p_e_p_i_t_a_s-_cryptocurrency__p_e_p_i_t_a_s-_cryptocurrency__r_e_a_d_m_e \- PEPITAS 
C cryptocurrency\&.
.PP
\fC\fP.SH "CODING STYLE"
.PP
.SS "Coding case"
.IP "\(bu" 2
\fIFunctions\fP, \fIvariables\fP and \fIfilenames\fP must be written in \fCsnake_case\fP\&.
.IP "\(bu" 2
\fIStructures\fP must be written in \fCPascalCase\fP\&.
.IP "\(bu" 2
\fIConstants\fP or \fIMACRO\fP must be written in \fCUPPER_SNAKE_CASE\fP\&.
.PP
.SS "Tests"
Each function must be tested before \fBmarked as done\fP\&. To create a test function, you must write it in the \fCtest/\fP directory and call the file \fCfilename_test\&.c\fP and its functions \fCfunctionname_test\fP\&. Note that the test file must be at the same relative place than his real function
.PP
exemple : if you want to test \fC\fBinit_server()\fP\fP in the file \fC\fBnetwork/client\&.c\fP\fP, you must write the test in \fCtest/network/client_test\&.c\fP and call the test function \fCinit_server_test()\fP 
