.TH "Neighbour" 3 "Thu Apr 22 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neighbour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "int \fBserver_sockfd\fP"
.br
.ti -1c
.RI "int \fBclient_sockfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file client\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int client_sockfd"

.PP
Definition at line 13 of file client\&.h\&.
.SS "int family"

.PP
Definition at line 10 of file client\&.h\&.
.SS "char* hostname"

.PP
Definition at line 11 of file client\&.h\&.
.SS "int server_sockfd"

.PP
Definition at line 12 of file client\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
