.TH "Neighbour" 3 "Sun Jul 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neighbour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file network\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int family"

.PP
Definition at line 35 of file network\&.h\&.
.SS "char* hostname"

.PP
Definition at line 36 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
