.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/network/network.c" 3 "Tue Jun 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/network/network.c
.SH SYNOPSIS
.br
.PP
\fC#include 'network/client\&.h'\fP
.br
\fC#include 'network/network\&.h'\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBNeighbour\fP \fBHARD_CODED_ADDR\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBNeighbour\fP HARD_CODED_ADDR[]"
\fBInitial value:\fP
.PP
.nf
=
{
    {AF_INET, "34\&.72\&.117\&.116"}, 
    {AF_INET, "127\&.0\&.0\&.1"}  
}
.fi
.PP
Definition at line 5 of file network\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
