.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/plebe.c" 3 "Sun Jul 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/plebe.c
.SH SYNOPSIS
.br
.PP
\fC#include 'validation/plebe\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBplebe_adhere_block\fP (\fBBlock\fP *block)"
.br
.RI "Adhere a block, write it locally\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int plebe_adhere_block (\fBBlock\fP * block)"

.PP
Adhere a block, write it locally\&. 
.PP
\fBParameters\fP
.RS 4
\fIblock\fP The block to adhere 
.RE
.PP
\fBReturns\fP
.RS 4
0 if success, 2 if need to sync error, 1 if data corrupted error 
.RE
.PP

.PP
Definition at line 7 of file plebe\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
