.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/cryptosystem/rsa.c" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/cryptosystem/rsa.c
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptosystem/rsa\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRSA_NUM_E\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_keys\fP (\fB__attribute__\fP((unused)) char *password)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RSA_NUM_E   3"

.PP
Definition at line 2 of file rsa\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void get_keys (\fB__attribute__\fP((unused)) char * password)"

.PP
Definition at line 7 of file rsa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
