.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/cryptosystem/rsa.c" 3 "Thu Apr 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/cryptosystem/rsa.c
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptosystem/rsa\&.h'\fP
.br
\fC#include 'core/blockchain/wallet\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRSA_NUM_E\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_keys\fP ()"
.br
.RI "Get the keys object\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RSA_NUM_E   3"

.PP
Definition at line 16 of file rsa\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void get_keys ()"

.PP
Get the keys object\&. 
.PP
Definition at line 21 of file rsa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
