.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/cryptosystem/rsa.h" 3 "Mon Apr 19 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/cryptosystem/rsa.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRSA_KEY_SIZE\fP   366"
.br
.ti -1c
.RI "#define \fBRSA_FILE_TOTAL_SIZE\fP   426"
.br
.ti -1c
.RI "#define \fBRSA_BEGIN_SIZE\fP   31"
.br
.ti -1c
.RI "#define \fBRSA_END_SIZE\fP   29"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBget_keys\fP ()"
.br
.RI "Get the keys object\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RSA_BEGIN_SIZE   31"

.PP
Definition at line 6 of file rsa\&.h\&.
.SS "#define RSA_END_SIZE   29"

.PP
Definition at line 7 of file rsa\&.h\&.
.SS "#define RSA_FILE_TOTAL_SIZE   426"

.PP
Definition at line 5 of file rsa\&.h\&.
.SS "#define RSA_KEY_SIZE   366"

.PP
Definition at line 4 of file rsa\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void get_keys ()"

.PP
Get the keys object\&. 
.PP
Definition at line 21 of file rsa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
