.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/network/send_data.c" 3 "Tue Apr 20 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/network/send_data.c
.SH SYNOPSIS
.br
.PP
\fC#include 'network/network\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsend_client_list\fP (int sockfd)"
.br
.RI "Sends my client list to a node via 'sockfd'\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int send_client_list (int sockfd)"

.PP
Sends my client list to a node via 'sockfd'\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockfd\fP The sock FD 
.RE
.PP
\fBReturns\fP
.RS 4
0 if success, -1 otherwise 
.RE
.PP

.PP
Definition at line 3 of file send_data\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
