.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/network/send_data.c" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/network/send_data.c
.SH SYNOPSIS
.br
.PP
\fC#include 'network/send_data\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsend_client_list\fP (char who, int sockfd, char *sockip)"
.br
.RI "Sends my client list to a node via 'sockfd'\&. "
.ti -1c
.RI "void \fBsend_get_blocks\fP (\fBconnection\fP *cc)"
.br
.RI "Sends get blocks\&. "
.ti -1c
.RI "void \fBsend_actual_height\fP (int fd, \fBinfos_st\fP *infos)"
.br
.ti -1c
.RI "void \fBsend_reject_demand\fP (int fd)"
.br
.ti -1c
.RI "void \fBsend_send_block\fP (int fd, size_t height)"
.br
.ti -1c
.RI "void \fBsend_pending_transaction_list\fP (int fd)"
.br
.ti -1c
.RI "void \fBsend_send_pending_transaction\fP (int fd, time_t txid)"
.br
.ti -1c
.RI "void \fBsend_get_pending_transaction\fP (int fd, time_t txid)"
.br
.ti -1c
.RI "void \fBsend_epoch_block\fP (\fBconnection\fP *cc)"
.br
.ti -1c
.RI "void \fBsend_vote_fd\fP (\fBconnection\fP *cc)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void send_actual_height (int fd, \fBinfos_st\fP * infos)"

.PP
Definition at line 58 of file send_data\&.c\&.
.SS "int send_client_list (char who, int sockfd, char * sockip)"

.PP
Sends my client list to a node via 'sockfd'\&. 
.PP
\fBParameters\fP
.RS 4
\fIsockfd\fP The sock FD 
.RE
.PP
\fBReturns\fP
.RS 4
0 if success, -1 otherwise 
.RE
.PP

.PP
Definition at line 3 of file send_data\&.c\&.
.SS "void send_epoch_block (\fBconnection\fP * cc)"

.PP
Definition at line 173 of file send_data\&.c\&.
.SS "void send_get_blocks (\fBconnection\fP * cc)"

.PP
Sends get blocks\&. 
.PP
Definition at line 52 of file send_data\&.c\&.
.SS "void send_get_pending_transaction (int fd, time_t txid)"

.PP
Definition at line 165 of file send_data\&.c\&.
.SS "void send_pending_transaction_list (int fd)"

.PP
Definition at line 104 of file send_data\&.c\&.
.SS "void send_reject_demand (int fd)"

.PP
Definition at line 65 of file send_data\&.c\&.
.SS "void send_send_block (int fd, size_t height)"

.PP
Definition at line 71 of file send_data\&.c\&.
.SS "void send_send_pending_transaction (int fd, time_t txid)"

.PP
Definition at line 127 of file send_data\&.c\&.
.SS "void send_vote_fd (\fBconnection\fP * cc)"

.PP
Definition at line 209 of file send_data\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
