.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/validation/stake.h" 3 "Fri Apr 16 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/validation/stake.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpush_stake\fP (size_t amount)"
.br
.RI "Push an amount on the stake\&. "
.ti -1c
.RI "int \fBpop_stake\fP (size_t amount)"
.br
.RI "Pops an amount on the stake\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int pop_stake (size_t amount)"

.PP
Pops an amount on the stake\&. This will broadcast a stake pop on the network\&.
.PP
\fBSee also\fP
.RS 4
The stake account public key is '1'
.RE
.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount to pop 
.RE
.PP
\fBReturns\fP
.RS 4
0 if the broadcast succeeds, else returns -1 
.RE
.PP

.SS "int push_stake (size_t amount)"

.PP
Push an amount on the stake\&. This will broadcast a stake push on the network\&.
.PP
\fBSee also\fP
.RS 4
The stake account public key is '1'
.RE
.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount to push 
.RE
.PP
\fBReturns\fP
.RS 4
0 if the broadcast succeeds, else returns -1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
