.TH "th_arg" 3 "Tue Jun 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
th_arg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <network\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBinfos_st\fP * \fBinfos\fP"
.br
.ti -1c
.RI "\fBconnection\fP * \fBclient_con\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file network\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBconnection\fP* client_con"

.PP
Definition at line 67 of file network\&.h\&.
.SS "\fBinfos_st\fP* infos"

.PP
Definition at line 66 of file network\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
