.TH "Transaction" 3 "Mon Apr 19 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transaction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTransactionData\fP * \fBtransaction_data\fP"
.br
.ti -1c
.RI "size_t \fBsignature_len\fP"
.br
.ti -1c
.RI "char * \fBtransaction_signature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file transaction\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t signature_len"

.PP
Definition at line 32 of file transaction\&.h\&.
.SS "\fBTransactionData\fP* transaction_data"

.PP
Definition at line 30 of file transaction\&.h\&.
.SS "char* transaction_signature"

.PP
Definition at line 33 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
