.TH "TransactionData" 3 "Fri Jun 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBmagic\fP"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "RSA * \fBsender_public_key\fP"
.br
.ti -1c
.RI "RSA * \fBreceiver_public_key\fP"
.br
.ti -1c
.RI "size_t \fBamount\fP"
.br
.ti -1c
.RI "size_t \fBsender_remaining_money\fP"
.br
.ti -1c
.RI "size_t \fBreceiver_remaining_money\fP"
.br
.ti -1c
.RI "time_t \fBtransaction_timestamp\fP"
.br
.ti -1c
.RI "char \fBcause\fP [512]"
.br
.ti -1c
.RI "char \fBasset\fP [512]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file block\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t amount"

.PP
Definition at line 40 of file block\&.h\&.
.SS "char asset"

.PP
Definition at line 48 of file block\&.h\&.
.SS "char cause"

.PP
Definition at line 47 of file block\&.h\&.
.SS "char magic"

.PP
Definition at line 34 of file block\&.h\&.
.SS "RSA * receiver_public_key"

.PP
Definition at line 39 of file block\&.h\&.
.SS "size_t receiver_remaining_money"

.PP
Definition at line 42 of file block\&.h\&.
.SS "RSA * sender_public_key"

.PP
Definition at line 38 of file block\&.h\&.
.SS "size_t sender_remaining_money"

.PP
Definition at line 41 of file block\&.h\&.
.SS "time_t transaction_timestamp"

.PP
Definition at line 43 of file block\&.h\&.
.SS "char type"

.PP
Definition at line 35 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
