.TH "Transaction" 3 "Sat May 8 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transaction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTransactionData\fP \fBtransaction_data\fP"
.br
.ti -1c
.RI "char \fBtransaction_signature\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file transaction\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBTransactionData\fP transaction_data"

.PP
Definition at line 45 of file transaction\&.h\&.
.SS "char transaction_signature[256]"

.PP
Definition at line 47 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
