.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/blockchain/transaction.h" 3 "Sun Jul 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/blockchain/transaction.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/sha\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include 'blockchain/wallet\&.h'\fP
.br
\fC#include 'blockchain/blockchain_header\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTransactionData\fP"
.br
.ti -1c
.RI "struct \fBTransaction\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRANSACTION_DATA_SIZE\fP   sizeof(size_t) * 3 + sizeof(time_t) + (512 * 2)"
.br
.ti -1c
.RI "#define \fBTRANSACTION_SIZE\fP   sizeof(size_t) + 2048 + \fBTRANSACTION_DATA_SIZE\fP"
.br
.ti -1c
.RI "#define \fBT_TYPE_DEFAULT\fP   0"
.br
.ti -1c
.RI "#define \fBT_TYPE_ADD_STAKE\fP   1"
.br
.ti -1c
.RI "#define \fBT_TYPE_WITHDRAW_STAKE\fP   2"
.br
.ti -1c
.RI "#define \fBT_TYPE_REWARD_STAKE\fP   3"
.br
.ti -1c
.RI "#define \fBT_TYPE_PUNISH_STAKE\fP   4"
.br
.ti -1c
.RI "#define \fBTRANS_T\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBTransactionData\fP \fBTransactionData\fP"
.br
.ti -1c
.RI "typedef struct \fBTransaction\fP \fBTransaction\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsend_money\fP (size_t amount, u_int64_t receiver_public_key)"
.br
.RI "Send 'amount' money to 'receiver_public_key'\&. This will broadcast a transaction to the network\&. "
.ti -1c
.RI "void \fBwrite_transactiondata\fP (\fBTransactionData\fP *transaction, int fd)"
.br
.RI "Serialize a TransactionData* structure\&. "
.ti -1c
.RI "void \fBwrite_transaction\fP (\fBTransaction\fP *transaction, int fd)"
.br
.RI "Serialize a Transaction* structure\&. "
.ti -1c
.RI "void \fBget_transaction_data\fP (\fBTransaction\fP *trans, char **buff, size_t *index)"
.br
.RI "Get the transaction data object\&. "
.ti -1c
.RI "void \fBconvert_data_to_transactiondata\fP (\fBTransactionData\fP *transactiondata, int fd)"
.br
.RI "Convert serialized TransactionData* to TransactionData*\&. "
.ti -1c
.RI "void \fBload_transaction\fP (\fBTransaction\fP *transaction, int fd)"
.br
.RI "Load a serialized Transaction* structure\&. "
.ti -1c
.RI "\fBTransaction\fP * \fBload_pending_transaction\fP (time_t timestamp)"
.br
.RI "Load a transaction in the pending transaction (pdt) directory\&. "
.ti -1c
.RI "void \fBadd_pending_transaction\fP (\fBTransaction\fP *transaction)"
.br
.RI "Add a transaction to the pending transaction (pdt) directory\&. "
.ti -1c
.RI "\fBTransaction\fP \fBcreate_new_transaction\fP (\fBinfos_st\fP *infos, char type, RSA *receiver_public_key, size_t amount, char cause[512], char asset[512])"
.br
.RI "Create a new transaction\&. "
.ti -1c
.RI "void \fBflush_pending_transactions\fP (\fBTransaction\fP **transactions, size_t nb_transactions)"
.br
.RI "Delete block transactions in the pending transaction (pdt) directory if the block is valid\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define T_TYPE_ADD_STAKE   1"

.PP
Definition at line 22 of file transaction\&.h\&.
.SS "#define T_TYPE_DEFAULT   0"

.PP
Definition at line 21 of file transaction\&.h\&.
.SS "#define T_TYPE_PUNISH_STAKE   4"

.PP
Definition at line 25 of file transaction\&.h\&.
.SS "#define T_TYPE_REWARD_STAKE   3"

.PP
Definition at line 24 of file transaction\&.h\&.
.SS "#define T_TYPE_WITHDRAW_STAKE   2"

.PP
Definition at line 23 of file transaction\&.h\&.
.SS "#define TRANS_T"

.PP
Definition at line 28 of file transaction\&.h\&.
.SS "#define TRANSACTION_DATA_SIZE   sizeof(size_t) * 3 + sizeof(time_t) + (512 * 2)"

.PP
Definition at line 18 of file transaction\&.h\&.
.SS "#define TRANSACTION_SIZE   sizeof(size_t) + 2048 + \fBTRANSACTION_DATA_SIZE\fP"

.PP
Definition at line 19 of file transaction\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBTransaction\fP \fBTransaction\fP"

.SS "typedef struct \fBTransactionData\fP \fBTransactionData\fP"

.SH "Function Documentation"
.PP 
.SS "void add_pending_transaction (\fBTransaction\fP * transaction)"

.PP
Add a transaction to the pending transaction (pdt) directory\&. 
.PP
\fBParameters\fP
.RS 4
\fItransaction\fP The transaction to add 
.RE
.PP

.PP
Definition at line 140 of file transaction\&.c\&.
.SS "void convert_data_to_transactiondata (\fBTransactionData\fP * transactiondata, int fd)"

.PP
Convert serialized TransactionData* to TransactionData*\&. 
.PP
\fBParameters\fP
.RS 4
\fItransactiondata\fP The returned TransactionData* 
.br
\fIfd\fP The serialized \fBTransactionData\fP FD 
.RE
.PP

.PP
Definition at line 88 of file transaction\&.c\&.
.SS "\fBTransaction\fP create_new_transaction (\fBinfos_st\fP * infos, char type, RSA * receiver_public_key, size_t amount, char cause[512], char asset[512])"

.PP
Create a new transaction\&. 
.PP
\fBParameters\fP
.RS 4
\fIinfos\fP Shared information object 
.br
\fItype\fP The type of transaction 
.br
\fIreceiver_public_key\fP The receiver pkey 
.br
\fIamount\fP The amount of PEPITAS 
.br
\fIcause\fP The cause (deprecated) 
.br
\fIasset\fP The asset (deprecated) 
.RE
.PP
\fBReturns\fP
.RS 4
\fBTransaction\fP 
.RE
.PP

.PP
Definition at line 157 of file transaction\&.c\&.
.SS "void flush_pending_transactions (\fBTransaction\fP ** transactions, size_t nb_transactions)"

.PP
Delete block transactions in the pending transaction (pdt) directory if the block is valid\&. 
.PP
\fBParameters\fP
.RS 4
\fItransactions\fP block\&.blockdata\&.transactions 
.br
\fInb_transactions\fP number of transactions 
.RE
.PP

.PP
Definition at line 204 of file transaction\&.c\&.
.SS "void get_transaction_data (\fBTransaction\fP * trans, char ** buff, size_t * index)"

.PP
Get the transaction data object\&. 
.PP
\fBParameters\fP
.RS 4
\fItrans\fP The returned transaction 
.br
\fIbuff\fP The buffer with the serialized data 
.br
\fIindex\fP The buffer starting offset 
.RE
.PP

.PP
Definition at line 40 of file transaction\&.c\&.
.SS "\fBTransaction\fP* load_pending_transaction (time_t timestamp)"

.PP
Load a transaction in the pending transaction (pdt) directory\&. 
.PP
\fBParameters\fP
.RS 4
\fItimestamp\fP The timestamp of the transaction 
.RE
.PP
\fBReturns\fP
.RS 4
Transaction* 
.RE
.PP

.PP
Definition at line 127 of file transaction\&.c\&.
.SS "void load_transaction (\fBTransaction\fP * transaction, int fd)"

.PP
Load a serialized Transaction* structure\&. 
.PP
\fBParameters\fP
.RS 4
\fItransaction\fP The returned Transaction* 
.br
\fIfd\fP The serialized \fBTransaction\fP FD 
.RE
.PP

.PP
Definition at line 117 of file transaction\&.c\&.
.SS "int send_money (size_t amount, u_int64_t receiver_public_key)"

.PP
Send 'amount' money to 'receiver_public_key'\&. This will broadcast a transaction to the network\&. 
.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount to send 
.br
\fIreceiver_public_key\fP The receiver public key 
.RE
.PP
\fBReturns\fP
.RS 4
returns 0 if the broadcast succeeds, -1 otherwise 
.RE
.PP

.SS "void write_transaction (\fBTransaction\fP * transaction, int fd)"

.PP
Serialize a Transaction* structure\&. 
.PP
\fBParameters\fP
.RS 4
\fItransaction\fP The Transaction* structure to serialize 
.br
\fIfd\fP The output file FD 
.RE
.PP

.PP
Definition at line 34 of file transaction\&.c\&.
.SS "void write_transactiondata (\fBTransactionData\fP * transaction, int fd)"

.PP
Serialize a TransactionData* structure\&. 
.PP
\fBParameters\fP
.RS 4
\fItransaction\fP The TransactionData* structure to serialize 
.br
\fIfd\fP The output file FD 
.RE
.PP

.PP
Definition at line 3 of file transaction\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
