.TH "TransactionData" 3 "Fri Apr 16 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "RSA * \fBsender_public_key\fP"
.br
.ti -1c
.RI "RSA * \fBreceiver_public_key\fP"
.br
.ti -1c
.RI "RSA * \fBorganisation_public_key\fP"
.br
.ti -1c
.RI "size_t \fBamount\fP"
.br
.ti -1c
.RI "size_t \fBsender_remaining_money\fP"
.br
.ti -1c
.RI "size_t \fBreceiver_remaining_money\fP"
.br
.ti -1c
.RI "time_t \fBtransaction_timestamp\fP"
.br
.ti -1c
.RI "char \fBcause\fP [512]"
.br
.ti -1c
.RI "char \fBasset\fP [512]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file transaction\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t amount"

.PP
Definition at line 17 of file transaction\&.h\&.
.SS "char asset[512]"

.PP
Definition at line 25 of file transaction\&.h\&.
.SS "char cause[512]"

.PP
Definition at line 24 of file transaction\&.h\&.
.SS "RSA* organisation_public_key"

.PP
Definition at line 16 of file transaction\&.h\&.
.SS "RSA* receiver_public_key"

.PP
Definition at line 15 of file transaction\&.h\&.
.SS "size_t receiver_remaining_money"

.PP
Definition at line 19 of file transaction\&.h\&.
.SS "RSA* sender_public_key"

.PP
Definition at line 14 of file transaction\&.h\&.
.SS "size_t sender_remaining_money"

.PP
Definition at line 18 of file transaction\&.h\&.
.SS "time_t transaction_timestamp"

.PP
Definition at line 20 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
