.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/ui/ui.c" 3 "Fri Jun 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/ui/ui.c
.SH SYNOPSIS
.br
.PP
\fC#include 'ui/ui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBsetup\fP (void *args)"
.br
.RI "Setups the gtk widgets for the GUI\&. "
.ti -1c
.RI "void \fBchange_label_text\fP (GtkLabel *label, char *text)"
.br
.ti -1c
.RI "gboolean \fBset_block_viewer_plus\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBset_block_viewer_minus\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "void \fBset_block_viewer\fP (int height)"
.br
.ti -1c
.RI "void \fBadd_new_blockinfo\fP (size_t height, size_t transaction)"
.br
.ti -1c
.RI "void \fBupdate_sync\fP (size_t actual, size_t final)"
.br
.ti -1c
.RI "gboolean \fBon_main_window_delete\fP (GtkWidget *widget, \fB__attribute__\fP((unused)) gpointer data)"
.br
.RI "Destroys the window when it is closed\&. "
.ti -1c
.RI "void \fBon_main_window_destroy\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) gpointer data)"
.br
.ti -1c
.RI "gboolean \fBon_transaction_button_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "void \fBadd_transaction_with_pkey\fP (double amount, char *public_key, char *date)"
.br
.ti -1c
.RI "void \fBadd_transaction_with_contact\fP (double amount, char *public_key, char *date)"
.br
.ti -1c
.RI "void \fBadd_transaction_from_file\fP (double amount, char *public_key, char *date)"
.br
.ti -1c
.RI "void \fBload_transactions_from_file\fP ()"
.br
.ti -1c
.RI "gboolean \fBon_invest_button1_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_invest_button2_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_recover_button1_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_recover_button2_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_add_contact_button1_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBadd_contact\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "void \fBadd_contact_to_combobox\fP (char *name)"
.br
.ti -1c
.RI "void \fBadd_contacts_from_file\fP (char *name, char *public_key)"
.br
.ti -1c
.RI "void \fBload_contacts_from_file\fP ()"
.br
.ti -1c
.RI "char * \fBget_public_key_from_contacts\fP (const char *name)"
.br
.ti -1c
.RI "gboolean \fBon_create_key_but1_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_create_key_but2_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "gboolean \fBon_connect_but_press\fP (\fB__attribute__\fP((unused)) GtkWidget *widget, \fB__attribute__\fP((unused)) GdkEventKey *event, \fB__attribute__\fP((unused)) gpointer user_data)"
.br
.ti -1c
.RI "void \fBupdate_labels\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "GtkLabel * \fBbalance_1\fP"
.br
.ti -1c
.RI "GtkLabel * \fBbalance_2\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label1\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label2\fP"
.br
.ti -1c
.RI "GtkLabel * \fBstake_label3\fP"
.br
.ti -1c
.RI "GtkLabel * \fBsynchro_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBblock_amount_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBconnections_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBmempool_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBpublic_key_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBpassword_error_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBlatest_block_name1\fP"
.br
.ti -1c
.RI "GtkLabel * \fBlatest_block_name2\fP"
.br
.ti -1c
.RI "GtkLabel * \fBlatest_block_name3\fP"
.br
.ti -1c
.RI "GtkLabel * \fBerror_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBblock_height_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBtransa_number_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBtotal_transa_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBmagic_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBprev_block_valid_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBnb_validators_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBblock_error_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBblock_time_label\fP"
.br
.ti -1c
.RI "GtkLabel * \fBvalidators_votes_label\fP"
.br
.ti -1c
.RI "GtkEntry * \fBtransa_amount\fP"
.br
.ti -1c
.RI "GtkEntry * \fBrecipient_key\fP"
.br
.ti -1c
.RI "GtkEntry * \fBasset_entry\fP"
.br
.ti -1c
.RI "GtkEntry * \fBcause_entry\fP"
.br
.ti -1c
.RI "GtkEntry * \fBinvest_entry\fP"
.br
.ti -1c
.RI "GtkEntry * \fBrecover_entry\fP"
.br
.ti -1c
.RI "GtkEntry * \fBname_entry_con\fP"
.br
.ti -1c
.RI "GtkEntry * \fBpublic_key_entry_con\fP"
.br
.ti -1c
.RI "GtkEntry * \fBpassword_entry1\fP"
.br
.ti -1c
.RI "GtkEntry * \fBpassword_entry2\fP"
.br
.ti -1c
.RI "GtkEntry * \fBkey_entry\fP"
.br
.ti -1c
.RI "GtkTreeView * \fBtv_con\fP"
.br
.ti -1c
.RI "GtkTreeStore * \fBts_con\fP"
.br
.ti -1c
.RI "GtkTreeViewColumn * \fBcx1_con\fP"
.br
.ti -1c
.RI "GtkTreeViewColumn * \fBcx2_con\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr1_con\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr2_con\fP"
.br
.ti -1c
.RI "GtkTreeView * \fBtv_th\fP"
.br
.ti -1c
.RI "GtkTreeStore * \fBts_th\fP"
.br
.ti -1c
.RI "GtkTreeViewColumn * \fBcx1_th\fP"
.br
.ti -1c
.RI "GtkTreeViewColumn * \fBcx2_th\fP"
.br
.ti -1c
.RI "GtkTreeViewColumn * \fBcx3_th\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr1_th\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr2_th\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr3_th\fP"
.br
.ti -1c
.RI "GtkComboBox * \fBcontacts_combo\fP"
.br
.ti -1c
.RI "GtkListStore * \fBls_combo\fP"
.br
.ti -1c
.RI "GtkCellRenderer * \fBcr1_combo\fP"
.br
.ti -1c
.RI "GtkProgressBar * \fBprogress_bar_blockchain\fP"
.br
.ti -1c
.RI "size_t \fBblock_height\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "gboolean add_contact (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 595 of file ui\&.c\&.
.SS "void add_contact_to_combobox (char * name)"

.PP
Definition at line 624 of file ui\&.c\&.
.SS "void add_contacts_from_file (char * name, char * public_key)"

.PP
Definition at line 632 of file ui\&.c\&.
.SS "void add_new_blockinfo (size_t height, size_t transaction)"

.PP
Definition at line 322 of file ui\&.c\&.
.SS "void add_transaction_from_file (double amount, char * public_key, char * date)"

.PP
Definition at line 480 of file ui\&.c\&.
.SS "void add_transaction_with_contact (double amount, char * public_key, char * date)"

.PP
Definition at line 460 of file ui\&.c\&.
.SS "void add_transaction_with_pkey (double amount, char * public_key, char * date)"

.PP
Definition at line 440 of file ui\&.c\&.
.SS "void change_label_text (GtkLabel * label, char * text)"

.PP
Definition at line 233 of file ui\&.c\&.
.SS "char* get_public_key_from_contacts (const char * name)"

.PP
Definition at line 667 of file ui\&.c\&.
.SS "void load_contacts_from_file ()"

.PP
Definition at line 641 of file ui\&.c\&.
.SS "void load_transactions_from_file ()"

.PP
Definition at line 490 of file ui\&.c\&.
.SS "gboolean on_add_contact_button1_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 586 of file ui\&.c\&.
.SS "gboolean on_connect_but_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 746 of file ui\&.c\&.
.SS "gboolean on_create_key_but1_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 686 of file ui\&.c\&.
.SS "gboolean on_create_key_but2_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 701 of file ui\&.c\&.
.SS "gboolean on_invest_button1_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 525 of file ui\&.c\&.
.SS "gboolean on_invest_button2_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 534 of file ui\&.c\&.
.SS "gboolean on_main_window_delete (GtkWidget * widget, \fB__attribute__\fP((unused)) gpointer data)"

.PP
Destroys the window when it is closed\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP The main window of the GUI 
.RE
.PP
\fBReturns\fP
.RS 4
gboolean Error code 
.RE
.PP

.PP
Definition at line 358 of file ui\&.c\&.
.SS "void on_main_window_destroy (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) gpointer data)"

.PP
Definition at line 367 of file ui\&.c\&.
.SS "gboolean on_recover_button1_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 555 of file ui\&.c\&.
.SS "gboolean on_recover_button2_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 564 of file ui\&.c\&.
.SS "gboolean on_transaction_button_press (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 374 of file ui\&.c\&.
.SS "void set_block_viewer (int height)"

.PP
Definition at line 270 of file ui\&.c\&.
.SS "gboolean set_block_viewer_minus (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 253 of file ui\&.c\&.
.SS "gboolean set_block_viewer_plus (\fB__attribute__\fP((unused)) GtkWidget * widget, \fB__attribute__\fP((unused)) GdkEventKey * event, \fB__attribute__\fP((unused)) gpointer user_data)"

.PP
Definition at line 238 of file ui\&.c\&.
.SS "void* setup (void * args)"

.PP
Setups the gtk widgets for the GUI\&. 
.PP
\fBReturns\fP
.RS 4
int Returns 1 if there is an error, 0 otherwise 
.RE
.PP

.PP
Definition at line 80 of file ui\&.c\&.
.SS "void update_labels ()"

.PP
Definition at line 796 of file ui\&.c\&.
.SS "void update_sync (size_t actual, size_t final)"

.PP
Definition at line 339 of file ui\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "GtkEntry* asset_entry"

.PP
Definition at line 50 of file ui\&.c\&.
.SS "GtkLabel* balance_1"

.PP
Definition at line 24 of file ui\&.c\&.
.SS "GtkLabel* balance_2"

.PP
Definition at line 25 of file ui\&.c\&.
.SS "GtkLabel* block_amount_label"

.PP
Definition at line 30 of file ui\&.c\&.
.SS "GtkLabel* block_error_label"

.PP
Definition at line 45 of file ui\&.c\&.
.SS "size_t block_height = 0"

.PP
Definition at line 78 of file ui\&.c\&.
.SS "GtkLabel* block_height_label"

.PP
Definition at line 39 of file ui\&.c\&.
.SS "GtkLabel* block_time_label"

.PP
Definition at line 46 of file ui\&.c\&.
.SS "GtkEntry* cause_entry"

.PP
Definition at line 51 of file ui\&.c\&.
.SS "GtkLabel* connections_label"

.PP
Definition at line 31 of file ui\&.c\&.
.SS "GtkComboBox* contacts_combo"

.PP
Definition at line 73 of file ui\&.c\&.
.SS "GtkCellRenderer* cr1_combo"

.PP
Definition at line 75 of file ui\&.c\&.
.SS "GtkCellRenderer* cr1_con"

.PP
Definition at line 63 of file ui\&.c\&.
.SS "GtkCellRenderer* cr1_th"

.PP
Definition at line 70 of file ui\&.c\&.
.SS "GtkCellRenderer* cr2_con"

.PP
Definition at line 64 of file ui\&.c\&.
.SS "GtkCellRenderer* cr2_th"

.PP
Definition at line 71 of file ui\&.c\&.
.SS "GtkCellRenderer* cr3_th"

.PP
Definition at line 72 of file ui\&.c\&.
.SS "GtkTreeViewColumn* cx1_con"

.PP
Definition at line 61 of file ui\&.c\&.
.SS "GtkTreeViewColumn* cx1_th"

.PP
Definition at line 67 of file ui\&.c\&.
.SS "GtkTreeViewColumn* cx2_con"

.PP
Definition at line 62 of file ui\&.c\&.
.SS "GtkTreeViewColumn* cx2_th"

.PP
Definition at line 68 of file ui\&.c\&.
.SS "GtkTreeViewColumn* cx3_th"

.PP
Definition at line 69 of file ui\&.c\&.
.SS "GtkLabel* error_label"

.PP
Definition at line 38 of file ui\&.c\&.
.SS "GtkEntry* invest_entry"

.PP
Definition at line 52 of file ui\&.c\&.
.SS "GtkEntry* key_entry"

.PP
Definition at line 58 of file ui\&.c\&.
.SS "GtkLabel* latest_block_name1"

.PP
Definition at line 35 of file ui\&.c\&.
.SS "GtkLabel* latest_block_name2"

.PP
Definition at line 36 of file ui\&.c\&.
.SS "GtkLabel* latest_block_name3"

.PP
Definition at line 37 of file ui\&.c\&.
.SS "GtkListStore* ls_combo"

.PP
Definition at line 74 of file ui\&.c\&.
.SS "GtkLabel* magic_label"

.PP
Definition at line 42 of file ui\&.c\&.
.SS "GtkLabel* mempool_label"

.PP
Definition at line 32 of file ui\&.c\&.
.SS "GtkEntry* name_entry_con"

.PP
Definition at line 54 of file ui\&.c\&.
.SS "GtkLabel* nb_validators_label"

.PP
Definition at line 44 of file ui\&.c\&.
.SS "GtkEntry* password_entry1"

.PP
Definition at line 56 of file ui\&.c\&.
.SS "GtkEntry* password_entry2"

.PP
Definition at line 57 of file ui\&.c\&.
.SS "GtkLabel* password_error_label"

.PP
Definition at line 34 of file ui\&.c\&.
.SS "GtkLabel* prev_block_valid_label"

.PP
Definition at line 43 of file ui\&.c\&.
.SS "GtkProgressBar* progress_bar_blockchain"

.PP
Definition at line 76 of file ui\&.c\&.
.SS "GtkEntry* public_key_entry_con"

.PP
Definition at line 55 of file ui\&.c\&.
.SS "GtkLabel* public_key_label"

.PP
Definition at line 33 of file ui\&.c\&.
.SS "GtkEntry* recipient_key"

.PP
Definition at line 49 of file ui\&.c\&.
.SS "GtkEntry* recover_entry"

.PP
Definition at line 53 of file ui\&.c\&.
.SS "GtkLabel* stake_label1"

.PP
Definition at line 26 of file ui\&.c\&.
.SS "GtkLabel* stake_label2"

.PP
Definition at line 27 of file ui\&.c\&.
.SS "GtkLabel* stake_label3"

.PP
Definition at line 28 of file ui\&.c\&.
.SS "GtkLabel* synchro_label"

.PP
Definition at line 29 of file ui\&.c\&.
.SS "GtkLabel* total_transa_label"

.PP
Definition at line 41 of file ui\&.c\&.
.SS "GtkEntry* transa_amount"

.PP
Definition at line 48 of file ui\&.c\&.
.SS "GtkLabel* transa_number_label"

.PP
Definition at line 40 of file ui\&.c\&.
.SS "GtkTreeStore* ts_con"

.PP
Definition at line 60 of file ui\&.c\&.
.SS "GtkTreeStore* ts_th"

.PP
Definition at line 66 of file ui\&.c\&.
.SS "GtkTreeView* tv_con"

.PP
Definition at line 59 of file ui\&.c\&.
.SS "GtkTreeView* tv_th"

.PP
Definition at line 65 of file ui\&.c\&.
.SS "GtkLabel* validators_votes_label"

.PP
Definition at line 47 of file ui\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
