.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/unit_testing.c" 3 "Sun Jun 13 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/unit_testing.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tests_macros\&.h'\fP
.br
\fC#include 'cryptosystem/rsa_test\&.h'\fP
.br
\fC#include 'cryptosystem/signature_test\&.h'\fP
.br
\fC#include 'network/client_test\&.h'\fP
.br
\fC#include 'blockchain/block_test\&.h'\fP
.br
\fC#include 'validation/validations_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBinfos_st\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBinfos_st\fP \fBinfos_st\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinfos_st\fP * \fBget_infos\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBinfos_st\fP * \fBac_infos\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBinfos_st\fP \fBinfos_st\fP"

.SH "Function Documentation"
.PP 
.SS "\fBinfos_st\fP* get_infos ()"

.PP
Definition at line 16 of file atrier\&.c\&.
.SS "int main ()"

.PP
Definition at line 22 of file unit_testing\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBinfos_st\fP* ac_infos"

.PP
Definition at line 18 of file unit_testing\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
