.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/unit_testing.c" 3 "Thu Apr 15 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/tests/unit_testing.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tests_macros\&.h'\fP
.br
\fC#include 'cryptosystem/signature_test\&.h'\fP
.br
\fC#include 'cryptosystem/rsa_test\&.h'\fP
.br
\fC#include 'network/client_test\&.c'\fP
.br
\fC#include 'core/blockchain/block_test\&.h'\fP
.br
\fC#include 'core/validation/validations_test\&.c'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 8 of file unit_testing\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
