.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/validations.c" 3 "Thu Apr 22 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/validation/validations.c
.SH SYNOPSIS
.br
.PP
\fC#include 'core/validation/validations\&.h'\fP
.br
\fC#include 'core/blockchain/block\&.h'\fP
.br
\fC#include 'cryptosystem/signature\&.h'\fP
.br
\fC#include 'cryptosystem/rsa\&.h'\fP
.br
\fC#include 'cryptosystem/hash\&.h'\fP
.br
\fC#include 'misc/math\&.h'\fP
.br
\fC#include 'misc/files\&.h'\fP
.br
\fC#include 'misc/safe\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNB_RSA_CHUNK\fP   2048 / 64"
.br
.ti -1c
.RI "#define \fBMAX_VALIDATORS_PER_BLOCK\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "uint16_t \fBdefine_nb_validators\fP (size_t n)"
.br
.ti -1c
.RI "RSA ** \fBget_next_committee\fP (size_t *nb_validators)"
.br
.RI "Get the 'next block' validators RSA public keys\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_VALIDATORS_PER_BLOCK   10000"

.PP
Definition at line 14 of file validations\&.c\&.
.SS "#define NB_RSA_CHUNK   2048 / 64"

.PP
Definition at line 13 of file validations\&.c\&.
.SH "Function Documentation"
.PP 
.SS "uint16_t define_nb_validators (size_t n)"

.PP
Definition at line 16 of file validations\&.c\&.
.SS "RSA** get_next_committee (size_t * nb_validators)"

.PP
Get the 'next block' validators RSA public keys\&. 
.PP
\fBParameters\fP
.RS 4
\fInb_validators\fP return value, the number of selected validators 
.RE
.PP
\fBSee also\fP
.RS 4
The 'next block' is referring to block after the last block available OFFLINE 
.RE
.PP
\fBReturns\fP
.RS 4
[*RSA] 
.RE
.PP

.PP
Definition at line 31 of file validations\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
