.TH "validators_state_item" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
validators_state_item
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <validators\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBvalidator_pkey\fP [\fBRSA_KEY_SIZE\fP]"
.br
.ti -1c
.RI "size_t \fBuser_stake\fP"
.br
.ti -1c
.RI "size_t \fBvalidator_power\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file validators\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t user_stake"

.PP
Definition at line 24 of file validators\&.h\&.
.SS "char validator_pkey[\fBRSA_KEY_SIZE\fP]"

.PP
Definition at line 23 of file validators\&.h\&.
.SS "size_t validator_power"

.PP
Definition at line 25 of file validators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
