.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/validation/validations.h" 3 "Sat Apr 10 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/headers/core/validation/validations.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "RSA ** \fBget_next_committee\fP (size_t *nb_validators)"
.br
.RI "Get the 'next block' validators RSA public keys\&. "
.ti -1c
.RI "ssize_t \fBget_amount\fP (RSA *public_key)"
.br
.RI "Searches how much money 'public_key' has\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "ssize_t get_amount (RSA * public_key)"

.PP
Searches how much money 'public_key' has\&. 
.PP
\fBParameters\fP
.RS 4
\fIpublic_key\fP The RSA public key 
.RE
.PP
\fBReturns\fP
.RS 4
The amount, or -1 in case of an error 
.RE
.PP

.SS "RSA** get_next_committee (size_t * nb_validators)"

.PP
Get the 'next block' validators RSA public keys\&. 
.PP
\fBParameters\fP
.RS 4
\fInb_validators\fP return value, the number of selected validators 
.RE
.PP
\fBSee also\fP
.RS 4
The 'next block' is referring to block after the last block available OFFLINE 
.RE
.PP
\fBReturns\fP
.RS 4
[*RSA] 
.RE
.PP

.PP
Definition at line 31 of file validations\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
