.TH "validators_state_header" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
validators_state_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <validators\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnb_validators\fP"
.br
.ti -1c
.RI "size_t \fBtotal_stake\fP"
.br
.ti -1c
.RI "size_t \fBblock_height_validity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file validators\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t block_height_validity"

.PP
Definition at line 18 of file validators\&.h\&.
.SS "size_t nb_validators"

.PP
Definition at line 16 of file validators\&.h\&.
.SS "size_t total_stake"

.PP
Definition at line 17 of file validators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
