.TH "Wallet" 3 "Sun Jul 28 2024" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wallet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "RSA * \fBpriv_key\fP"
.br
.ti -1c
.RI "RSA * \fBpub_key\fP"
.br
.ti -1c
.RI "size_t \fBamount\fP"
.br
.ti -1c
.RI "size_t \fBstake_amount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file wallet\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t amount"

.PP
Definition at line 15 of file wallet\&.h\&.
.SS "RSA* priv_key"

.PP
Definition at line 12 of file wallet\&.h\&.
.SS "RSA* pub_key"

.PP
Definition at line 13 of file wallet\&.h\&.
.SS "size_t stake_amount"

.PP
Definition at line 16 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
