.TH "/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/wallet.c" 3 "Mon Jun 14 2021" "PEPITAS CRYPTOCURRENCY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/PEPITAS-Cryptocurrency/PEPITAS-Cryptocurrency/src/core/blockchain/wallet.c
.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include 'blockchain/wallet\&.h'\fP
.br
\fC#include 'cryptosystem/rsa\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBWallet\fP * \fBget_my_wallet\fP ()"
.br
.RI "Get my wallet object\&. "
.ti -1c
.RI "int \fBcreate_account\fP ()"
.br
.RI "Creates an account in local and broadcasts the creation to the network\&. "
.ti -1c
.RI "void \fBadd_money_to_wallet\fP (size_t money)"
.br
.RI "Add money to my wallet\&. "
.ti -1c
.RI "void \fBremove_money_from_wallet\fP (size_t money)"
.br
.RI "Remove money from my wallet\&. "
.ti -1c
.RI "void \fBadd_money_to_stake\fP (size_t money)"
.br
.RI "Add money to my stake\&. "
.ti -1c
.RI "void \fBremove_money_from_stake\fP (size_t money)"
.br
.RI "Withdraw money from my stake\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_money_to_stake (size_t money)"

.PP
Add money to my stake\&. 
.PP
\fBParameters\fP
.RS 4
\fImoney\fP The amount of PEPITAS 
.RE
.PP

.PP
Definition at line 45 of file wallet\&.c\&.
.SS "void add_money_to_wallet (size_t money)"

.PP
Add money to my wallet\&. 
.PP
\fBParameters\fP
.RS 4
\fImoney\fP The amount of PEPITAS 
.RE
.PP

.PP
Definition at line 26 of file wallet\&.c\&.
.SS "int create_account ()"

.PP
Creates an account in local and broadcasts the creation to the network\&. 
.PP
\fBReturns\fP
.RS 4
0 if the broadcast succeeds, otherwise 1 
.RE
.PP

.PP
Definition at line 18 of file wallet\&.c\&.
.SS "\fBWallet\fP* get_my_wallet ()"

.PP
Get my wallet object\&. 
.PP
\fBReturns\fP
.RS 4
\fBWallet\fP 
.RE
.PP

.PP
Definition at line 6 of file wallet\&.c\&.
.SS "void remove_money_from_stake (size_t money)"

.PP
Withdraw money from my stake\&. 
.PP
\fBParameters\fP
.RS 4
\fImoney\fP The amount of PEPITAS 
.RE
.PP

.PP
Definition at line 54 of file wallet\&.c\&.
.SS "void remove_money_from_wallet (size_t money)"

.PP
Remove money from my wallet\&. 
.PP
\fBParameters\fP
.RS 4
\fImoney\fP The amount of PEPITAS 
.RE
.PP

.PP
Definition at line 34 of file wallet\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PEPITAS CRYPTOCURRENCY from the source code\&.
